# Generated by cucumber-sinatra. (2014-10-03 14:28:40 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/rockpaperscissors.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Rock_Paper_Scissors

class Rock_Paper_ScissorsWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  Rock_Paper_ScissorsWorld.new
end
